name: deploy-container

on:
  push:
    branches: [ main, init-project ]
    paths:
      - 'monorepo/container/**'

defaults:
  run:
    working-directory: 'monorepo/container'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: yarn
      - run: yarn build

      - uses: aws-actions/aws-cli@v2.4.5
      - run: s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest --size-only
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-central-1
