name: deploy-container

on:
  push:
    branches:
      - main
      - init-project
    paths:
      - 'monorepo/container/**'

default:
  run:
    working-directory: 'microfrontend/monorepo/container'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: yarn install
      - run: yarn build

#      - uses: shinyinc/action-aws-cli@v1.2
#      - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
#      - name: Deploy to S3 bucket
#        uses: aws-actions/aws-cli@v2.4.5
#        with:
#          args: s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest --size-only
#        env:
#        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        AWS_DEFAULT_REGION: eu-central-1
