name: deploy-container

on:
  push:
    branches: [ main, init-project ]
    paths:
      - 'monorepo/container/**'

defaults:
  run:
    working-directory: 'monorepo/container'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: yarn
      - run: yarn build
