name: deploy-server-test

on:
  push:
    branches:
      - main
      - add-auth-server
    paths:
      - 'server/**'

defaults:
  run:
    working-directory: 'server'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: yarn
      - run: yarn build
