name: deploy-server

on:
  push:
    branches: [ main, add-auth-server ]
    paths:
      - 'server/**'

defaults:
  run:
    working-directory: 'server'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - run: yarn
      - run: yarn build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: .
